baseURL = 'http://makethefinal.ca/'
languageCode = 'en-us'
title = 'Make The Final'
theme = "ananke"
publishDir = 'docs'
Paginate = 1000
SectionPagesMenu = "main"

[params]
  #author = "Andrew Flemming"
  twitter = "https://twitter.com/aflemm"
  description = "Memorable moments in curling punctuated by the poetic musings of Vic Rauter. A blog by Andrew Flemming."


  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"#"bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5