baseURL = 'https://makethefinal.ca/'
languageCode = 'en-us'
title = 'Make The Final'
theme = "ananke"
publishDir = 'docs'
Paginate = 1000
SectionPagesMenu = "about"
Copyright = "Andrew Flemming"

[outputs]
  home = [ "RSS", "HTML"]
  section  = ["HTML", "json"]
  page = ["HTML", "json"]
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

  [outputFormats.json]
    mediatype = "application/json"
    baseName = "data"


[menu]
[[menu.main]]
  identifier = 'random'
  name = 'Random'
  url = '/random/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 100
[[menu.main]]
  identifier = 'api'
  name = 'API'
  url = '/api/'
  weight = 5
[[menu.main]]
  identifier = 'submission'
  name = 'Submit'
  url = '/submit/'
  weight = 20

[params]
  author = "Vic Rauter"
  twitter = "https://twitter.com/aflemm"
  rss = "https://makethefinal.ca/feed.xml"
  instagram = "https://www.instagram.com/makethefinal.ca/"
  description = "Memorable moments in curling punctuated by the poetic musings of Vic Rauter. A blog by Andrew Flemming."
  favicon = "/img/favicon.ico" # Path to favicon file
  
  mainSections = ["posts"]

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"#"bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
  
  env = "production"